# Chart: https://github.com/helm/charts/tree/master/stable/postgresql
global:
  postgresql:
    postgresqlDatabase: yaes
    postgresqlUsername: yaesuser
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: monitoring
