# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gauravagarwalr/Yet-Another-Expense-Splitter

    docker:
      - image: circleci/golang:1.10
      - image: postgres:9.6
        environment:
          POSTGRES_PASSWORD=password

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-{{ checksum "Gopkg.lock" }}
            - go-

      - run:
          name: Install dep
          command: go get -u github.com/golang/dep/cmd/dep

      - run:
          name: Installing dependencies
          command: dep ensure

      - save_cache:
          key: go-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Running Tests
          command: make ci-test
          environment:
            DATABASE_URL: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
