# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER=ubuntu
          POSTGRES_DB=yaes-test

    working_directory: /go/src/github.com/gauravagarwalr/Yet-Another-Expense-Splitter
    steps:
      - checkout

      - run:
          name: Installing dependencies
          command: go get -v -t -d ./...
      - run:
          name: Running Tests
          command: make ci-test
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/yaes-test?sslmode=disable"
