# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  test:
    working_directory: /go/src/algogrit.com/yaes-server

    docker:
      - image: circleci/golang:1.14.2
      - image: postgres:9.6
        environment:
          POSTGRES_PASSWORD: password

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
            - go-mod-

      - run:
          name: Installing dependencies
          command: go mod download

      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - $GOPATH/pkg/mod

      - run:
          name: Running Tests
          command: make ci-test
          environment:
            DATABASE_URL: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"

  build-and-push-migration-image:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/migration.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/migration.tar | true
            docker images

      - run:
          name: Build application Docker image
          command: |
            docker build --build-arg PROJECT_NAME=migration -t gauravagarwalr/yaes-migration:latest  --cache-from gauravagarwalr/yaes-migration .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/migration.tar gauravagarwalr/yaes-migration

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/migration.tar

      - deploy:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"

            docker push gauravagarwalr/yaes-migration:latest

            docker tag gauravagarwalr/yaes-migration:latest gauravagarwalr/yaes-migration:${CIRCLE_BRANCH}-${CIRCLE_WORKFLOW_ID}
            docker push gauravagarwalr/yaes-migration:${CIRCLE_BRANCH}-${CIRCLE_WORKFLOW_ID}
            docker tag gauravagarwalr/yaes-migration:latest gauravagarwalr/yaes-migration:${CIRCLE_BRANCH}-latest
            docker push gauravagarwalr/yaes-migration:${CIRCLE_BRANCH}-latest

  build-and-push-server-image:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/server.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/server.tar | true
            docker images

      - run:
          name: Build application Docker image
          command: |
            docker build --build-arg PROJECT_NAME=server -t gauravagarwalr/yaes-server:latest  --cache-from gauravagarwalr/yaes-server .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/server.tar gauravagarwalr/yaes-server

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/server.tar

      - deploy:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"

            docker push gauravagarwalr/yaes-server:latest

            docker tag gauravagarwalr/yaes-server:latest gauravagarwalr/yaes-server:${CIRCLE_BRANCH}-${CIRCLE_WORKFLOW_ID}
            docker push gauravagarwalr/yaes-server:${CIRCLE_BRANCH}-${CIRCLE_WORKFLOW_ID}
            docker tag gauravagarwalr/yaes-server:latest gauravagarwalr/yaes-server:${CIRCLE_BRANCH}-latest
            docker push gauravagarwalr/yaes-server:${CIRCLE_BRANCH}-latest

workflows:
  test_and_deploy:
    jobs:
      - test:
          name: "go test"

      - build-and-push-migration-image:
          name: "Build & Push migration image"
          context: dockerhub
          requires:
            - go test

      - build-and-push-server-image:
          name: "Build & Push server image"
          context: dockerhub
          requires:
            - go test
