apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: yaes-server
  labels:
    app: yaes-monitor
    release: monitoring
spec:
  selector:
    matchLabels:
      app: yaes
  podMetricsEndpoints:
    - port: diagnostics
