apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaes-deployment
  labels:
    app: yaes
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: yaes
  template:
    metadata:
      labels:
        app: yaes
    spec:
      restartPolicy: Always
      # initContainers:
      # - name: migrations
      #   image: gauravagarwalr/yaes-migration:latest
      #   imagePullPolicy: IfNotPresent
      containers:
      - name: yaes-server
        image: gauravagarwalr/yaes-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-server
          containerPort: 8080
        - name: diagnostics
          containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: DB_USER
          value: yaesuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yaes-db-postgresql
              key: postgresql-password
        - name: DB_HOST
          value: yaes-db-postgresql
        - name: DB_NAME
          value: yaes
        - name: DB_SSL_MODE
          value: disable
        - name: GO_APP_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: DIAGNOSTICS_PORT
          value: "8000"

---

apiVersion: v1
kind: Service
metadata:
  name: "yaes"
  labels:
    app: yaes
spec:
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: yaes
  type: ClusterIP
